name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      ftoken: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJjaXBoZXJ0ZXh0IjoiaEdPYXh5SnhNRHJFOUNLaDJla3NIQW9SVzdray1tTnRoOWw0TmZPMS1wMXRGMC1RdVF3ZUtzMzREOGpsVmRKNWZMVzhCTFBubFg1R1hncndlU0hJUHhSUEU4eVpTZFREYkNJTkRIZTNEdEdwU2VVbDlQTEVUMnMtZ1ppZDZPQW9zckdxS19EMEhGUkhwNkRTQWR4Z3FaTjJhRzl1YTlsdlhRZjMyd1lJNUU0eEFHWEllMTJiZ2hCWlJ0YmpzQ2R1UUIyNGtmZXRxblNJR3R4S1FpaW1TRGZZUi1YTWE1VEZEVEpfS24wRjB3RUVoYUFNdjJRUCIsImVuY3J5cHRlZF9rZXkiOiJGWEJKalYwSjlOVFB2cVRHRjVTckY5ZzRZM1JMRlQ2SjhUTE9vT0xUZzBJIiwiaGVhZGVyIjp7Iml2IjoicGg4UENJb3JFajBJVERGUSIsInRhZyI6IkU1d2t6bGV5TlBIMHRaOXEzOFBMd0EifSwiaXYiOiIwRlVBNkRQaTBYalpUM2c0IiwicHJvdGVjdGVkIjoiZXlKaGJHY2lPaUpCTWpVMlIwTk5TMWNpTENKbGJtTWlPaUpCTWpVMlIwTk5JbjAiLCJ0YWciOiJLUDRubDNSSnVxYmlLYndhSjJZMmhRIn0.cSi7dhhnCVqAkFyyXSBk4YTTAckIQeFM3beIUf80Cg4QSpVXjh1AXOu_QXBPwumdBQL3fAqznwu61YkCJ-BZHg
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
           docker pull fluidattacks/forces:new
           docker images
           docker run --rm -i fluidattacks/forces:new forces --token ${{env.ftoken}} -vv
