name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      ftoken: "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJjaXBoZXJ0ZXh0IjoiLU1ELXFfZDRpVkZvYnduZnMtQWVqMG9ZOHBCaUVXY3hvQkdWYkYxQWJtb0VXYlhKRmFSVTRsblE5d1RZbGp3Mzh1ZUtvbUMwWHdRNmlYVkxzQ0d1a0ctMXAxMVRuUWVQaDM0VUFCWHBBMFpRaDVxTmpoQ013UHpOVXl2elhBNlVhMkptem1JRnB1TVdsOVlUV1JQTF9yMDJybDk4Z1RrQlk3QkZ0Q09xajIzWFBDbUR1RWxuaXN1MHdRcllQQnhLSlFFTE5YbUdVM0NhSU9JYWFYWGc4TjFXQ3BSYmNHTUdfTUdwS0dhVmdBbE1tREdZdmthOSIsImVuY3J5cHRlZF9rZXkiOiJja3BpNGtTUG1LOERzenZpeHMwelVtYXRrRG5sWlJ2VkZ6dmZGSEVYZnN3IiwiaGVhZGVyIjp7Iml2IjoiZWRvUEdjRzNYNFBhMG85RCIsInRhZyI6IlliOWV5WjEwLVRlSW5mMXAtTGNqUEEifSwiaXYiOiJodmxrUmt5RmZGcGpIUmJoIiwicHJvdGVjdGVkIjoiZXlKaGJHY2lPaUpCTWpVMlIwTk5TMWNpTENKbGJtTWlPaUpCTWpVMlIwTk5JbjAiLCJ0YWciOiJiV0t4Y2w2V3dnN0tQNjRoSlk4SnFBIn0.oavPyEb9mBJHkInuJ_chqh2QgXO7WIZkfcceLDX7vz7VKa9ltyP4ep5mIqDM8pcyhzlibTTmMEm2ye4XD5Kpnw"
      
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
           docker pull fluidattacks/forces:new
           docker images
           docker run --rm -i fluidattacks/forces:new forces --token ${{env.ftoken}} -vv
