name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      ftoken: ${{ secrets.FTOKEN }}
      
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
           docker pull fluidattacks/forces:new
           docker images
           docker run --rm -i fluidattacks/forces:new forces --token ${{env.ftoken}} -vv
